name: ziquid
recipe: drupal9
config:
  webroot: web
  php: '7.4'
  via: apache
  database: mariadb
  xdebug: false
  composer_version: "2-latest"
# excludes:
#   - vendor
#   - node_modules
#   - modules/contrib
proxy:
  appserver:
    - ziquid.lndo.site
    - zds.lndo.site
    - cheek.lndo.site
services:
  appserver:
    build:
      - composer install
    build_as_root:
      - apt update -y && apt install nano -y
    composer_version: "2-latest"
    overrides:
      environment:
        PHP_MEMORY_LIMIT: 1024M
    scanner: false
  database:
    type: mariadb:10.4
    portforward: true
    creds:
      user: drupal
      password: drupal
      database: ziquid
  zds:
    type: mariadb:10.4
    portforward: true
    creds:
      user: drupal
      password: drupal
      database: zds
  cheek:
    type: mariadb:10.4
    portforward: true
    creds:
      user: drupal
      password: drupal
      database: cheek
      run_as_root:
        # Creates the extra databases as root since the app user does not have those privileges
        - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS cheek; GRANT ALL PRIVILEGES ON cheek.* TO 'drupal'@'%' IDENTIFIED by 'drupal';"
tooling:
  edit:
    service: appserver
    cmd: nano
    description: edit this file inside the container with nano
