display:
  default:
    display_title: Pamantayan
    display_options:
      exposed_form:
        options:
          reset_button_label: 'Ibalik sa pamantayan'
      arguments:
        tid:
          exception:
            title: Lahat
  page_1:
    display_title: Pahina
