label: 'Mga puna'
display:
  default:
    display_title: Pamantayan
    display_options:
      title: 'Mga puna'
      fields:
        subject:
          label: Paksa
        name:
          label: 'May akda'
        changed:
          label: Nabago
        operations:
          label: 'Mga operasyon'
      pager:
        options:
          tags:
            next: 'susunod ›'
            previous: '‹ nakaraan'
            first: '« una'
            last: 'huli »'
      exposed_form:
        options:
          submit_button: Salain
          reset_button_label: 'Ibalik sa pamantayan'
      empty:
        area_text_custom:
          content: 'Walang magagamit na mga puna.'
      filters:
        subject:
          expose:
            label: Paksa
        langcode:
          expose:
            label: Wika
      use_more_text: 'marami pa'
  page_published:
    display_title: 'Mga nailathalang puna'
    display_options:
      menu:
        title: 'Mga puna'
  page_unapproved:
    display_options:
      fields:
        subject:
          label: Paksa
        name:
          label: 'May akda'
        changed:
          label: Nabago
        operations:
          label: 'Mga operasyon'
      filters:
        subject:
          expose:
            label: Paksa
        langcode:
          expose:
            label: Wika
