label: 'Termo de taxonomia'
description: 'Conteúdo pertencente a um certo termo de taxonomia.'
display:
  default:
    display_title: Padrão
    display_options:
      pager:
        options:
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Tudo -'
            offset_label: Deslocamento
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Ascendente
          sort_desc_label: Decrescente
      arguments:
        tid:
          exception:
            title: Tudo
  page_1:
    display_title: Página
