display:
  default:
    display_title: Principal
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Ascendente
          sort_desc_label: Decrescente
      pager:
        options:
          tags:
            previous: '‹ Voltar'
            next: 'Avançar ›'
            first: '« Primeiro'
            last: 'Último »'
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Tudo -'
            offset_label: Deslocamento
      fields:
        name:
          separator: ', '
        pid:
          separator: ', '
        css_style:
          separator: ', '
        operations:
          label: Operações
      filters:
        name:
          expose:
            label: Nome
        field_tags_target_id:
          expose:
            label: Tags
  page_1:
    display_title: Página
