label: Comentários
description: 'Localizar e gerenciar comentários.'
display:
  default:
    display_title: Padrão
    display_options:
      title: Comentários
      fields:
        comment_bulk_form:
          action_title: Ação
        subject:
          label: Assunto
        name:
          label: Autor
        entity_id:
          label: 'Enviado em'
        changed:
          label: Atualizado
        operations:
          label: Operações
      pager:
        options:
          tags:
            next: 'próximo ›'
            previous: '‹ anterior'
            first: '« início'
            last: 'fim »'
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Tudo -'
            offset_label: Deslocamento
      exposed_form:
        options:
          submit_button: Filtrar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Ascendente
          sort_desc_label: Decrescente
      empty:
        area_text_custom:
          content: 'Nenhum comentário disponível.'
      filters:
        subject:
          expose:
            label: Assunto
        combine:
          expose:
            label: 'Nome do autor'
        langcode:
          expose:
            label: Idioma
      use_more_text: mais
  page_published:
    display_title: 'Comentários publicados'
    display_options:
      display_description: 'A lista de comentários aprovados.'
      menu:
        title: Comentários
        description: 'Comentários publicados'
  page_unapproved:
    display_title: 'Comentários não aprovados'
    display_options:
      fields:
        comment_bulk_form:
          action_title: Ação
        subject:
          label: Assunto
        name:
          label: Autor
        entity_id:
          label: 'Enviado em'
        changed:
          label: Atualizado
        operations:
          label: Operações
      filters:
        subject:
          expose:
            label: Assunto
        combine:
          expose:
            label: 'Nome do Autor'
        langcode:
          expose:
            label: Idioma
      display_description: 'A lista de comentários não aprovados.'
      menu:
        title: 'Comentários não aprovados'
        description: 'Comentários não aprovados'
