display:
  default:
    display_title: Principal
    display_options:
      exposed_form:
        options:
          submit_button: Filtrar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Ascendente
          sort_desc_label: Decrescente
      pager:
        options:
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Tudo -'
            offset_label: Deslocamento
      fields:
        path:
          label: Caminho
        count:
          label: Contar
        langcode:
          label: Idioma
        redirect_404_operations:
          label: Operações
      filters:
        path:
          expose:
            label: Caminho
        langcode:
          expose:
            label: Idioma
      title: 'Conserta páginas 404'
  page_1:
    display_title: Página
