palette:
  top: '#058e21'
  bottom: '#1dc346'
  bg: '#ffffff'
  sidebar: '#f6f6f2'
  sidebarborders: '#f9f9f9'
  footer: '#292929'
  titleslogan: '#fffeff'
  text: '#3b3b3b'
  link: '#0071b3'
logo: 'public://color/bartik-61a69065/logo.svg'
stylesheets:
  - 'public://color/bartik-61a69065/colors.css'
files:
  - 'public://color/bartik-61a69065/logo.svg'
  - 'public://color/bartik-61a69065/colors.css'
