_core:
  default_config_hash: 7LkiviGITIpniIOOIzpuxR7r4XzqqYN_cwu0fb0kx1M
content_access_roles_gids:
  anonymous: 1
  authenticated: 2
  contributor: 3
  account_owner: 4
  administrator: 5
content_access_node_type:
  help_page: 'a:3:{s:8:"view_own";a:3:{i:0;s:13:"authenticated";i:1;s:13:"account_owner";i:2;s:13:"administrator";}s:4:"view";a:3:{i:0;s:13:"authenticated";i:1;s:13:"account_owner";i:2;s:13:"administrator";}s:8:"per_node";i:1;}'
