_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_translation: 0
  contact: 0
  content_access: 0
  contextual: 0
  custom_breadcrumbs: 0
  datetime: 0
  dblog: 0
  displayrole: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editablefields: 0
  editor: 0
  entity_clone: 0
  entity_reference_revisions: 0
  eva: 0
  field: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  hierarchy_manager: 0
  history: 0
  image: 0
  imce: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  libraries: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  menus_attribute: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_type_permissions: 0
  path: 0
  path_alias: 0
  rabbit_hole: 0
  rdf: 0
  recaptcha: 0
  redirect: 0
  redirect_404: 0
  redirect_domain: 0
  responsive_image: 0
  rh_node: 0
  rh_taxonomy: 0
  search: 0
  shortcut: 0
  system: 0
  system_stream_wrapper: 0
  taxonomy: 0
  taxonomy_tree: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_add_button: 0
  views_tree: 0
  views_ui: 0
  visjs: 0
  content_translation: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  seven: 0
  adminimal_theme: 0
  pam_theme: 0
  bootstrap_barrio: 0
  bootstrap_barrio_subtheme: 0
  stark: 0
profile: standard
