cloneable_entities:
  - block
  - block_content
  - block_content_type
  - captcha_point
  - comment_type
  - comment
  - config_split
  - contact_form
  - contact_message
  - custom_breadcrumbs
  - editor
  - field_config
  - field_storage_config
  - file
  - filter_format
  - hm_display_profile
  - image_style
  - imce_profile
  - configurable_language
  - language_content_settings
  - media_type
  - media
  - menu_link_content
  - node_type
  - node
  - path_alias
  - behavior_settings
  - rdf_mapping
  - redirect
  - responsive_image_style
  - rest_resource_config
  - search_page
  - shortcut_set
  - shortcut
  - action
  - menu
  - taxonomy_term
  - taxonomy_vocabulary
  - user
  - user_role
  - pathauto_pattern
  - view
  - paragraph
  - paragraphs_type
  - date_format
  - entity_form_mode
  - entity_view_display
  - entity_form_display
  - entity_view_mode
  - base_field_override
