_core:
  default_config_hash: h6dm-6Fu8tAsr8ABsk6CEK3NLl9HLZcG9zvPh5JNqpQ
hierarchy_manager: null
allowed_setup_plugins:
  hm_setup_taxonomy: hm_setup_taxonomy
  hm_setup_menu: 0
setup_plugin_settings:
  hm_setup_menu:
    display_profile: default
    bundle:
      account: 0
      admin: 0
      footer: 0
      main: 0
      tools: 0
  hm_setup_taxonomy:
    display_profile: default
    bundle:
      account_organization: account_organization
      tags: 0
