_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
session:
  parameter: lang
url:
  source: path_prefix
  prefixes:
    en: ''
    fil: fil
    pt-br: pt-br
    es: es
    '': null
  domains:
    en: ''
    fil: ''
    pt-br: ''
    es: ''
selected_langcode: site_default
