_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: b09aa8a8-21fa-40cc-b42e-d6ed6785b3dd
name: Pam
mail: pam@zds.group
slogan: ''
page:
  403: ''
  404: ''
  front: /node/7
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
