_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor5: 0
  comment: 0
  config: 0
  contact: 0
  content_access: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity_clone: 0
  entity_reference_revisions: 0
  entityqueue: 0
  entityqueue_smartqueue: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  gin_toolbar: 0
  google_tag: 0
  help: 0
  history: 0
  image: 0
  imce: 0
  inline_form_errors: 0
  layout_builder: 0
  layout_builder_tabs: 0
  layout_discovery: 0
  libraries: 0
  link: 0
  masquerade: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  menus_attribute: 0
  metatag: 0
  metatag_app_links: 0
  metatag_dc: 0
  metatag_facebook: 0
  metatag_favicons: 0
  metatag_mobile: 0
  metatag_open_graph: 0
  metatag_pinterest: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  metatag_views: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  rabbit_hole: 0
  recaptcha: 0
  redirect: 0
  redirect_domain: 0
  responsive_image: 0
  rh_node: 0
  rh_user: 0
  search: 0
  shortcut: 0
  simple_background_image_formatter: 0
  simple_sitemap: 0
  system: 0
  taxonomy: 0
  term_csv_export_import: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  upgrade_status: 0
  user: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_ui: 0
  webform: 0
  webform_access: 0
  webform_node: 0
  webform_submission_log: 0
  webform_ui: 0
  fontyourface: 1
  pathauto: 1
  typekit_api: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  claro: 0
  gin: 0
  stable: 0
  zuvipro: 0
profile: standard
