_core:
  default_config_hash: 5tuWovWYUcoR60VOYvthBtW6fYQ2GO3jLByGaSkCZAw
favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  use_default: true
sticky_header_option: 1
header_circle_slider: 1
header_circle_header: 1
circle_type: circle_border
all_icons_show: 1
facebook_url: ''
twitter_url: ''
instagram_url: ''
linkedin_url: ''
youtube_url: 'https://www.youtube.com/@flabbierlime92'
vimeo_url: ''
telegram_url: ''
whatsapp_url: ''
github_url: ''
vk_url: ''
social_new_icon_code: ''
slider_show: 0
slider_time: '10000'
slider_dots: 'true'
slider_nav: 'true'
slider_wave: 1
slider_code: ''
preloader_option: 1
fancy_cursor: 1
google_font: googlecdn
animated_content: 1
comment_user_pic: 1
node_author_pic: 0
node_tags: 0
font_icon_fontawesome: 0
fontawesome_five: 0
font_icon_material: 0
page_share_all: 1
page_share_page: 1
page_share_article: 1
page_share_book: 0
page_share_other: 0
page_share_front: 1
animated_sidebar_option: 1
front_sidebar: 0
footer_wave: 1
copyright_text: 1
copyright_text_custom: ''
scrolltotop_on: 1
cookie_message: 1
cookie_message_custom: ''
styling: 0
styling_code: ''
insert_head: 0
head_code: ''
insert_body_start: 0
body_start_code: ''
insert_body_end: 0
body_end_code: ''
