features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 0
  path: themes/custom/zds_theme/images/favicon.png
  mimetype: image/png
custom_css: 0
disable_google_fonts: 0
