form_settings:
  taxonomy_term:
    default_value: false
    disable: false
    hidden: false
  block_content:
    default_value: false
    disable: false
    hidden: false
  comment:
    default_value: false
    disable: false
    hidden: false
  contact_message:
    default_value: false
    disable: false
    hidden: false
  file:
    default_value: false
    disable: false
    hidden: false
  node:
    default_value: false
    disable: false
    hidden: false
  shortcut:
    default_value: false
    disable: false
    hidden: false
  user:
    default_value: false
    disable: false
    hidden: false
  menu_link_content:
    default_value: false
    disable: false
    hidden: false
  entity_subqueue:
    default_value: false
    disable: false
    hidden: false
  media:
    default_value: false
    disable: false
    hidden: false
  path_alias:
    default_value: false
    disable: false
    hidden: false
  redirect:
    default_value: false
    disable: false
    hidden: false
  webform_submission:
    default_value: false
    disable: false
    hidden: false
  font:
    default_value: false
    disable: false
    hidden: false
