_core:
  default_config_hash: r8uAx4mTBwCkgDFbdKCmhjgbb91BQ4HbWSYRKrlowMY
load_all_enabled_fonts: 0
enabled_fonts:
  - 'https://typekit.com/fonts/scriptorama-tradeshow-jf#n4'
  - 'https://typekit.com/fonts/abril-titling-condensed#n4'
  - 'https://typekit.com/fonts/abril-titling-condensed#i4'
  - 'https://typekit.com/fonts/abril-titling-condensed#n7'
  - 'https://typekit.com/fonts/abril-titling-condensed#i7'
  - 'https://typekit.com/fonts/ff-ernestine-web-pro#n7'
  - 'https://typekit.com/fonts/lust-script-display#n4'
  - 'https://typekit.com/fonts/abril-titling#n4'
  - 'https://typekit.com/fonts/abril-titling#i4'
  - 'https://typekit.com/fonts/abril-titling#n7'
  - 'https://typekit.com/fonts/abril-titling#i7'
  - 'https://typekit.com/fonts/cabazon#n4'
  - 'https://typekit.com/fonts/adelle-web#n4'
  - 'https://typekit.com/fonts/warnock-pro-subhead#n4'
  - 'https://typekit.com/fonts/warnock-pro-subhead#i4'
  - 'https://typekit.com/fonts/warnock-pro-subhead#n7'
  - 'https://typekit.com/fonts/warnock-pro-subhead#i7'
  - 'https://typekit.com/fonts/roboto-mono#n4'
  - 'https://typekit.com/fonts/roboto-mono#n7'
  - 'https://typekit.com/fonts/jaf-facitweb#n4'
  - 'https://typekit.com/fonts/jaf-facitweb#i4'
  - 'https://typekit.com/fonts/jaf-facitweb#n7'
  - 'https://typekit.com/fonts/jaf-facitweb#i7'
  - 'https://typekit.com/fonts/warnock-pro-caption#n4'
  - 'https://typekit.com/fonts/warnock-pro-caption#i4'
  - 'https://typekit.com/fonts/warnock-pro-caption#n7'
  - 'https://typekit.com/fonts/warnock-pro-caption#i7'
  - 'https://typekit.com/fonts/source-sans-pro#n4'
  - 'https://typekit.com/fonts/source-sans-pro#i4'
  - 'https://typekit.com/fonts/source-sans-pro#n6'
  - 'https://typekit.com/fonts/source-sans-pro#i6'
