<?php

/**
 * @file
 * Lists available colors and color schemes for the TaraPro theme.
 */

$info = [
  // Available colors and color labels used in theme.
  'fields' => [
    'top' => t('Primary Color'),
    'header_top' => t('Primary Color Light'),
    'bottom' => t('Header background'),
    'menu' => t('Main menu Color'),
    'bg' => t('Main background'),
    'sidebar' => t('Light Color'),
    'text' => t('Text color'),
    'heading' => t('Heading color'),
    'border'  => t('Border Color'),
    'social_icon' => t('Secondry color'),
  ],
  // Pre-defined color schemes.
  'schemes' => [
    'default' => [
      'title' => t('TaraPro (default)'),
      'colors' => [
        'top' => '#d6620e',
        'header_top' => '#f2e8dd',
        'bottom' => '#ffffff',
        'menu' => '#212121',
        'bg' => '#f9f6f3',
        'sidebar' => '#fffbf6',
        'text' => '#4a4a4a',
        'heading' => '#222222',
        'border'  => '#dbdbd3',
        'social_icon' => '#a7bd43',
      ],
    ],
  ],

  // CSS files (excluding @import) to rewrite with new color scheme.
  'css' => [
    'css/colors.css',
  ],

  // Files to copy.
  'copy' => [
    'logo.svg',
  ],

  // Gradient definitions.
  'gradients' => [
    [
      // (x, y, width, height).
      'dimension' => [0, 0, 0, 0],
      // Direction of gradient ('vertical' or 'horizontal').
      'direction' => 'vertical',
      // Keys of colors to use for the gradient.
      'colors' => ['top', 'bottom'],
    ],
  ],

  // Preview files.
  'preview_library' => 'tarapro/color.preview',
  'preview_html' => 'color/preview.html',

  // Attachments.
  '#attached' => [
    'drupalSettings' => [
      'color' => [
        // Put the logo path into JavaScript for the live preview.
        'logo' => theme_get_setting('logo.url', 'tarapro'),
      ],
    ],
  ],
];
